-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Янв 06 2021 г., 00:40
-- Версия сервера: 10.3.22-MariaDB
-- Версия PHP: 7.4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `shop`
--

-- --------------------------------------------------------

--
-- Структура таблицы `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `descmini` varchar(500) NOT NULL,
  `descmax` text NOT NULL,
  `price` int(111) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `products`
--

INSERT INTO `products` (`id`, `name`, `image`, `descmini`, `descmax`, `price`) VALUES
(1, 'Samsung', '9hq.webp', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sit quo eligendi repellat? Quisquam dignissimos nesciunt odit quibusdam quia iste voluptatem ratione ea corporis? Ut a, eum corrupti repellendus libero.', 8000),
(2, 'Samsung Note 9', 'ru-galaxy-a21s-a217-sm-a217fzbnser-front-248940800.webp', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\n', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet dicta voluptatum laudantium asperiores est commodi voluptate iure cum unde, obcaecati ullam excepturi, tempora suscipit dolorem, maxime magni pariatur sint vel.\r\n', 12000),
(3, 'lg', 'Без названия(1).jfif', 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\n', 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, odio. Velit, labore, veritatis. Magni molestias voluptas perferendis maiores. Aliquid explicabo, placeat laudantium tenetur dolorem optio magni soluta aperiam porro reiciendis.\r\n', 9000),
(5, 'HP', 'ru-galaxy-a21s-a217-sm-a217fzbnser-front-248940800.webp', 'Lorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\n', 'Lorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas temporibus quo corrupti ratione error! Dicta voluptatem quisquam dolorem ab qui fugit dolorum harum facere quia laudantium praesentium, pariatur ipsam ratione.\r\nLorem ipsum dolor, sit amet, consectetur adipisicing elit. Voluptas te', 40000),
(6, 'Samsung', 'ru-galaxy-a21s-a217-sm-a217fzbnser-front-248940800.webp', 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\n', 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\nLorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium id iste earum voluptatibus, dicta explicabo, libero eum at assumenda illo quidem perferendis nobis corrupti blanditiis facere? Iure nobis in, nulla.\r\n', 80000),
(7, 'Samsung', 'ru-galaxy-a21s-a217-sm-a217fzbnser-front-248940800.webp', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\n', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorem magni, alias cumque? Architecto quibusdam laborum in aspernatur expedita, eos ad ex. Omnis, doloremque! Dolorum, voluptatum laborum unde ullam fugiat!\r\n', 60000);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
